export const olistCaseStudy = {
  slug: "olist-excel-analytics",
  title: "Olist Order Delivery Analysis",
  subtitle: "An Excel case study of order status, delivery speed, and fulfilment reliability.",
  sourceFile: "olist_orders_analysis.xlsx",
  role: "Independent Excel data analysis project completed for skills development.",
  completionDate: "14 May 2026",
  completionDateEvidence: "Verified from the workbook's last-modified metadata.",
  datasetLabel: "olist_orders_dataset",
  dataset: {
    name: "Brazilian E-Commerce Public Dataset by Olist",
    publisher: "Olist",
    source: "Kaggle",
    url: "https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce",
    accessedDate: "14 July 2026",
    attribution: "This project uses the Brazilian E-Commerce Public Dataset by Olist, originally published by Olist on Kaggle. Sheikh Suhel Ahmed independently analyzed the data in Excel for skills development and did not collect the original transaction data.",
  },
  period: "4 September 2016 – 17 October 2018",
  rows: 99_441,
  fields: 10,
  metrics: [
    { label: "Total orders", value: "99,441" },
    { label: "Delivered orders", value: "96,478" },
    { label: "Average delivery", value: "12.5 days" },
    { label: "On-time rate", value: "91.9%" },
    { label: "Late orders", value: "7,827" },
    { label: "Late rate", value: "8.1%" },
  ],
  statusDistribution: [
    { label: "Delivered", value: 96_478 },
    { label: "Shipped", value: 1_107 },
    { label: "Canceled", value: 625 },
    { label: "Unavailable", value: 609 },
    { label: "Invoiced", value: 314 },
    { label: "Processing", value: 301 },
    { label: "Created", value: 5 },
    { label: "Approved", value: 2 },
  ],
  yearlyVolume: [
    { label: "2016", value: 329 },
    { label: "2017", value: 45_101 },
    { label: "2018", value: 54_011 },
  ],
  deliveryClassification: [
    { label: "On Time", value: 88_649 },
    { label: "Late", value: 7_827 },
    { label: "Unknown", value: 2_965 },
  ],
  techniques: [
    "Structured Excel table over the order-level dataset",
    "IF, AND, OR, and DAYS formulas filled across 99,441 rows",
    "Three pivot tables for order status, purchase year, and delivery classification",
    "KPI summary for order counts, delivery time, and timeliness rates",
    "Bar and line charts linked to pivot outputs",
    "Missing-date handling through an explicit Unknown classification",
  ],
  pivots: [
    {
      title: "Order status",
      purpose: "Counts orders across eight fulfilment statuses.",
      range: "Analysis!A1:B10",
    },
    {
      title: "Purchase year",
      purpose: "Counts orders for 2016, 2017, and 2018.",
      range: "Analysis!C1:D5",
    },
    {
      title: "Delivery classification",
      purpose: "Separates On Time, Late, and Unknown orders.",
      range: "Analysis!E1:F5",
    },
  ],
  charts: [
    {
      title: "Order Distribution by Status",
      type: "Bar chart",
      source: "Analysis!A2:B10",
    },
    {
      title: "Order Volume by Purchase Year",
      type: "Line chart",
      source: "Analysis!C2:D5",
    },
  ],
  findings: [
    "The workbook contains 99,441 unique orders, of which 96,478 are marked delivered.",
    "Average delivery time in the KPI summary is 12.5 days.",
    "Among orders with known delivery timing, 91.9% are on time and 8.1% are late.",
    "The delivery classification pivot contains 88,649 On Time, 7,827 Late, and 2,965 Unknown orders.",
    "The purchase-year pivot contains 329 orders in 2016, 45,101 in 2017, and 54,011 in 2018.",
    "The order-status pivot records 625 canceled orders and 1,107 orders still marked shipped.",
  ],
  recommendations: [
    "Use the available approval, carrier, customer-delivery, and estimated-delivery timestamps to isolate where late-order delays occur.",
    "Resolve missing actual or estimated delivery dates behind the 2,965 Unknown classifications before deeper timeliness analysis.",
    "Track the on-time and late-rate KPIs consistently so delivery reliability remains visible as order volume changes.",
    "Review the 7,827 late orders as a dedicated exception group instead of relying only on the overall delivery average.",
  ],
  skills: [
    "Excel formulas",
    "Pivot tables",
    "KPI design",
    "Data classification",
    "Operational analysis",
    "Charting",
    "Quality checks",
  ],
} as const;
